apiVersion: v1
kind: Service
metadata:
  name: case-service
spec:
  type: NodePort
  selector:
    app: java-app
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
      nodePort: 30055